---
# visudo 登録
- name: postgres user sudores
  lineinfile:
    dest: /etc/sudoers.d/postgres
    owner: root
    group: root
    mode: 0440
    line: "%vagrant ALL=(postgres) NOPASSWD: ALL"
    state: present
    create: yes
    validate: "visudo -cf %s"

# 初期化
- name: postgresql initdb
  shell: service postgresql-{{ pg_version1 }} initdb
         creates=/var/lib/pgsql/{{ pg_version1 }}/data/postgresql.conf

# 設定ファイル転送
- name: Replace postgresql.conf
  copy: src=postgresql.conf dest=/var/lib/pgsql/{{ pg_version1 }}/data/postgresql.conf
- name: Replace pg_hba.conf
  template: src=pg_hba.conf.j2 dest=/var/lib/pgsql/{{ pg_version1 }}/data/pg_hba.conf

- name: postgres起動
  service: name="postgresql-{{ pg_version1 }}" state=started  enabled=yes